name: Notify Discord on Issue Comment

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ðŸ“ **${{ github.actor }}** commented on issue [#${{ github.event.issue.number }}](${{ github.event.comment.html_url }}):
            > ${{ github.event.comment.body }}
